### ISSUE TITLE
Issue about Standard App

### ISSUE THREAD

**Issue by sunningcan-0323** [derekbeaton/ONDRIApps#2]
@ahnjedid @derekbeaton 

Hi,

My team members and I have tried to use the most recently updated Standards app and it sometimes will quit by itself (After we click "Check Standards "). However, if we restart R Studio, the apps works fine. Thank you so much!

Thank you,
Vonna

**Comment by ahnjedid** [comment]
Hi Vonna,

Could you please take a screenshot of the error you are getting next time the app crashes? That'll allow me to pinpoint the source of the error.

Cheers,
Jed

**Comment by ahnjedid** [comment]
![ss](https://user-images.githubusercontent.com/22105889/72466971-f94f2080-37a7-11ea-87e2-9bdebb0cf6a0.png)

Hi Vonna,

The dplyr select function was being masked by a select function from another library that you loaded in your console. When you refreshed your RStudio, all libraries get cleared, which is why the app was able to run again. I have fixed this issue and pushed the patch to GitHub. Issue resolved and closed.

Cheers,
Jed

**Comment by sunningcan-0323** [comment]
Hi Jed,

Thanks for fixing the issue!

Much thanks,
Vonna
